# Generated by Django 4.0.4 on 2022-06-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name']},
        ),
    ]
